[build]
  publish = "public"
  functions = "netlify/functions"

# Thêm khối này để lên lịch chạy cho function 'check-devices'
[functions."check-devices"]
  # Cú pháp cron: chạy mỗi 5 phút
  schedule = "*/5 * * * *"
